"""
Django settings for se_groupwork project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uk#%!syv3zy%pz_j)ud--fla#f-jxin(@gds$i*!_kgaucb*i-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_extensions",
    'rest_framework',
    'rest_framework.authtoken', 
    'rest_framework_simplejwt',
    'drf_spectacular',
    'webspider',
    'user',
    'remoteAI',
    'article_selector',
]

# 配置Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

SPECTACULAR_SETTINGS = {
    # 项目基本信息
    'TITLE': '微信公众号管理系统 API',  # 改为项目总体名称
    'DESCRIPTION': """
    完整的微信公众号内容管理系统API文档
    
    ## 功能模块
    - 用户认证管理（注册、登录、资料修改）
    - 公众号订阅管理  
    - 文章收藏功能
    - 浏览历史记录
    - 文章推送功能
    
    ## 技术栈
    - Django + Django REST Framework
    - JWT身份认证
    - OpenAPI 3.0规范
    """,
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    
    # 多应用支持配置
    # 'SCHEMA_PATH_PREFIX': '/api/',  # 只包含/api/开头的路径
    # 'SCHEMA_PATH_PREFIX_TRIM': True,
    
    # 标签分组配置（重要！）
    'TAGS': [
        {
            'name': '用户认证',
            'description': '用户注册、登录、JWT令牌管理'
        },
        {
            'name': '用户资料', 
            'description': '用户个人信息管理和修改'
        },
        {
            'name': '订阅管理',
            'description': '公众号订阅功能'
        },
        {
            'name': '收藏管理',
            'description': '文章收藏功能'
        },
        {
            'name': '历史记录',
            'description': '用户浏览记录管理'
        },
        {
            'name': '文章推送',
            'description': '按时间、推荐或其他条件获取推文列表'
        }
    ],
    
    # 其他优化配置
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
        'expandResponses': '200,201',
    }, 
    
    'SECURITY': [{'bearerAuth': []}],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'se_groupwork.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'se_groupwork.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'se',      # 数据库名
        'USER': 'root',           # 数据库用户
        'PASSWORD': os.getenv('MYSQL_PASSWORD'),       # 数据库密码
        'HOST': 'localhost',              # 数据库地址
        'PORT': '3306',                   # 数据库端口
        'OPTIONS': {
            'charset': 'utf8mb4',         # 支持emoji等特殊字符
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT认证优先
        'rest_framework.authentication.SessionAuthentication',        # Session认证
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
#  这里将时间设置为北京时间，以便与公众号文章时间对应
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.User'

DEFAULT_PUBLIC_ACCOUNTS = [
    "清华大学",
    "清华紫荆之声", 
    "清华大学学生会",
    "清华大学社会实践",
    "清华大学学生公益",
    "清华大学学生社团",
    "清华体育",
    "清华大学信息服务",
    "乐学",
    "学在清华",
    "清华后勤服务",
    "清华家园网",
    "艾生权",
    "行在清华",
    "食在清华",
    "平安清华",
    "清华时事大讲堂",
    "文素THU",
    "清华小五爷园",
    "清新时报",
    "水木有礼",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

BASE_URL = 'http://127.0.0.1:8000' 