# Generated by Django 5.2.7 on 2025-10-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公众号名称')),
                ('icon_url', models.TextField(blank=True, verbose_name='图标URL')),
                ('fakeid', models.CharField(blank=True, max_length=100, verbose_name='Biz标识')),
                ('last_crawl_time', models.DateTimeField(blank=True, null=True, verbose_name='最后爬取时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微信公众号',
                'verbose_name_plural': '微信公众号',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='webspider_p_name_ecea88_idx'), models.Index(fields=['fakeid'], name='webspider_p_fakeid_e85380_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('article_url', models.URLField(unique=True, verbose_name='文章链接')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('crawl_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('summary', models.TextField(verbose_name='文章总结')),
                ('key_info', models.TextField(verbose_name='关键信息')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='webspider.publicaccount', verbose_name='所属公众号')),
            ],
            options={
                'verbose_name': '微信文章',
                'verbose_name_plural': '微信文章',
                'ordering': ['-publish_time'],
                'unique_together': {('account', 'article_url')},
            },
        ),
    ]
