# Generated by Django 5.2.7 on 2025-11-27 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cookies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cookies", models.TextField(verbose_name="Cookies")),
                ("token", models.CharField(max_length=20, verbose_name="Token")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "Cookies",
                "verbose_name_plural": "Cookies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="公众号名称")),
                (
                    "icon",
                    models.ImageField(
                        blank=True, upload_to="icons/", verbose_name="图标"
                    ),
                ),
                (
                    "fakeid",
                    models.CharField(blank=True, max_length=30, verbose_name="Biz标识"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认公众号"),
                ),
                (
                    "last_crawl_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后爬取时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "微信公众号",
                "verbose_name_plural": "微信公众号",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="webspider_p_name_ecea88_idx"),
                    models.Index(
                        fields=["fakeid"], name="webspider_p_fakeid_e85380_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="文章标题")),
                ("content", models.TextField(blank=True, verbose_name="文章内容")),
                (
                    "author",
                    models.CharField(blank=True, max_length=20, verbose_name="作者"),
                ),
                ("article_url", models.URLField(unique=True, verbose_name="文章链接")),
                (
                    "publish_time",
                    models.DateTimeField(blank=True, verbose_name="发布时间"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="文章总结")),
                ("key_info", models.TextField(blank=True, verbose_name="关键信息")),
                (
                    "tags",
                    models.CharField(blank=True, max_length=20, verbose_name="标签"),
                ),
                (
                    "tags_vector",
                    models.JSONField(default=list, verbose_name="标签向量"),
                ),
                (
                    "semantic_vector",
                    models.JSONField(default=list, verbose_name="语义向量"),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="covers/", verbose_name="封面URL"
                    ),
                ),
                (
                    "public_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="webspider.publicaccount",
                        verbose_name="所属公众号",
                    ),
                ),
            ],
            options={
                "verbose_name": "微信文章",
                "verbose_name_plural": "微信文章",
                "ordering": ["-publish_time"],
                "unique_together": {("public_account", "publish_time")},
            },
        ),
    ]
