# Generated by Django 5.2.7 on 2025-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webspider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies', models.TextField(verbose_name='Cookies')),
                ('token', models.CharField(max_length=100, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Cookies',
                'verbose_name_plural': 'Cookies',
                'ordering': ['-created_at'],
            },
        ),
    ]
