# Generated by Django 5.2.7 on 2025-12-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webspider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='subscription_count',
            field=models.IntegerField(default=0, verbose_name='被订阅数'),
        ),
    ]
