# Generated by Django 5.2.7 on 2025-12-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webspider', '0002_publicaccount_subscription_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='article_count',
            field=models.IntegerField(default=0, verbose_name='文章数'),
        ),
    ]
