# Generated by Django 5.2.7 on 2025-10-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webspider', '0002_cookies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='crawl_time',
        ),
    ]
