# Generated by Django 5.2.7 on 2025-12-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webspider', '0003_publicaccount_article_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='relevant_time',
            field=models.JSONField(default=list, verbose_name='相关时间'),
        ),
    ]
