# Generated by Django 5.2.7 on 2025-12-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webspider', '0004_article_relevant_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='文章标题'),
        ),
    ]
