# Generated by Django 5.2.7 on 2025-11-27 11:25

import django.db.models.deletion
import django.utils.timezone
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("webspider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "该用户名已被占用。"},
                        help_text="必填，不超过20个字符。只能包含字母、数字和 @/./+/-/_ 字符。",
                        max_length=20,
                        unique=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        error_messages={"unique": "该邮箱地址已被占用。"},
                        max_length=254,
                        verbose_name="邮箱地址",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        error_messages={"unique": "该手机号已被占用。"},
                        max_length=11,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="用户头像图片",
                        null=True,
                        upload_to=user.models.user_avatar_path,
                        verbose_name="头像",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="简短的个人介绍，最多500字",
                        max_length=500,
                        verbose_name="个人简介",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="标记用户是否可以登录到管理员站点。",
                        verbose_name="员工状态",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="标记用户是否被视为活跃用户。取消选中而不是删除账户。",
                        verbose_name="活跃状态",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="注册时间"
                    ),
                ),
                (
                    "subscription_count",
                    models.IntegerField(default=0, verbose_name="订阅公众号数"),
                ),
                (
                    "favorite_count",
                    models.IntegerField(default=0, verbose_name="收藏文章数"),
                ),
                (
                    "history_count",
                    models.IntegerField(default=0, verbose_name="活跃浏览历史数"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webspider.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webspider.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-favorited_at"],
                "unique_together": {("user", "article")},
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscribe_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "public_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webspider.publicaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-subscribe_at"],
                "unique_together": {("user", "public_account")},
            },
        ),
    ]
