# Generated by Django 5.2.7 on 2025-10-18 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': '该用户名已被占用。'}, help_text='必填。150个字符或更少。只能包含字母、数字和 @/./+/-/_ 字符。', max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(error_messages={'unique': '该邮箱地址已被占用。'}, max_length=254, unique=True, verbose_name='邮箱地址')),
                ('nickname', models.CharField(blank=True, help_text='用户的显示名称', max_length=50, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, help_text='用户头像图片', null=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, help_text='简短的个人介绍，最多500字', max_length=500, verbose_name='个人简介')),
                ('is_active', models.BooleanField(default=True, help_text='标记用户是否活跃。取消选中此项而不是删除用户。', verbose_name='活跃状态')),
                ('is_staff', models.BooleanField(default=False, help_text='标记用户是否可以登录到管理员站点。', verbose_name='员工状态')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动')),
                ('article_read_count', models.IntegerField(default=0, verbose_name='阅读文章数')),
                ('subscription_count', models.IntegerField(default=0, verbose_name='订阅公众号数')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-date_joined'],
            },
        ),
    ]
