# Generated by Django 5.2.7 on 2025-12-12 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_is_superuser_user_user_permissions_and_more'),
        ('webspider', '0003_publicaccount_article_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('remind', models.BooleanField(default=False, verbose_name='是否提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webspider.article', verbose_name='相关文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '待办',
                'verbose_name_plural': '待办',
                'ordering': ['start_time', 'id'],
                'indexes': [models.Index(fields=['user', 'start_time'], name='user_todo_user_id_449f54_idx'), models.Index(fields=['user', 'end_time'], name='user_todo_user_id_c9f787_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gte', models.F('start_time')), ('end_time__isnull', True), _connector='OR'), name='todo_end_after_start')],
            },
        ),
    ]
