# Generated by Django 5.2.7 on 2025-12-03 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_preference', models.JSONField(default=dict, help_text='{"公众号id": 权重}', verbose_name='公众号偏好')),
                ('tag_preference', models.JSONField(default=list, help_text='16个标签的权重', verbose_name='标签偏好')),
                ('keyword_preference', models.JSONField(default=list, help_text='偏好向量', verbose_name='关键词偏好')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户key')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
                'ordering': ['-updated_at'],
            },
        ),
    ]
